// SPDX-FileCopyrightText: 2026 ave
// SPDX-License-Identifier: MIT OR EUPL-1.2

/**
 * Names for the codes a boarding pass is written in.
 *
 * BCBP names nothing. Its airports are three letter IATA codes and its
 * airlines two letter designators, so both tables exist only to turn a pass
 * back into somewhere and someone. They are generated by
 * scripts/build-airports.py and scripts/build-airlines.py and refreshed
 * monthly; the terms each one carries are in its `_note` and in
 * docs/credits.md, and the airline table's are the ones that bind.
 *
 * Both load on demand, so only flight tickets pay for them, and until they
 * arrive the codes show, which is what happened before the tables existed.
 *
 * What is deliberately not resolved: item 142, the three digit accounting
 * code, which is a different numbering that neither source records; and the
 * metropolitan area codes such as LON and NYC, which stand for a city rather
 * than an airport and are in no airport catalogue.
 */
import { isoAlpha2CountryName } from '../countries.ts';

/** Airport name, then the town it serves and its country where those are known. */
export type AirportEntry = [name: string, municipality?: string, country?: string];
export type AirportTable = Record<string, AirportEntry>;
export type AirlineTable = Record<string, string>;

interface AirlineOverride {
	name: string;
	/** Where the identification comes from. */
	source: string;
}

/**
 * The designators the build script will not choose for, plus anywhere this
 * repo has a better answer. Corrections go here rather than into the JSON, so
 * that regenerating stays a clean copy.
 *
 * Both entries below are a passenger airline and its cargo arm holding one
 * designator. A boarding pass is a passenger document, so the cargo operation
 * is not what a pass carrying LH or SQ means, but that is a fact about
 * boarding passes rather than one in the table, which is why the script
 * declines to guess and this map answers instead.
 */
const AIRLINE_OVERRIDES: Record<string, AirlineOverride> = {
	LH: { name: 'Lufthansa', source: 'Lufthansa Cargo shares the designator and flies no passengers' },
	SQ: {
		name: 'Singapore Airlines',
		source: 'Singapore Airlines Cargo shares the designator and flies no passengers'
	}
};

let airportCache: AirportTable | null = null;
let airportPending: Promise<AirportTable> | null = null;

export async function loadAirports(): Promise<AirportTable> {
	if (airportCache) return airportCache;
	airportPending ??= import('../data/airports.json').then((m) => {
		// A JSON import widens every row to string[]. The build script writes
		// the name first and drops trailing blanks, which is what the tuple says.
		airportCache = (m.default as unknown as { airports: AirportTable }).airports;
		return airportCache;
	});
	return airportPending;
}

let airlineCache: AirlineTable | null = null;
let airlinePending: Promise<AirlineTable> | null = null;

export async function loadAirlines(): Promise<AirlineTable> {
	if (airlineCache) return airlineCache;
	airlinePending ??= import('../data/airlines.json').then((m) => {
		airlineCache = (m.default as { airlines: AirlineTable }).airlines;
		return airlineCache;
	});
	return airlinePending;
}

const entry = (airports: AirportTable | null, code: string): AirportEntry | undefined =>
	code ? airports?.[code.toUpperCase()] : undefined;

/**
 * What to put where the code went. The code itself until the table lands, and
 * for the codes it does not cover, since that is what the pass prints.
 */
export function airportName(airports: AirportTable | null, code: string): string {
	return entry(airports, code)?.[0] ?? code;
}

/**
 * The town and country behind the name, for the places a name alone does not
 * settle: Dulles is in Dulles, and the pass says Washington.
 */
export function airportPlace(airports: AirportTable | null, code: string): string | null {
	const found = entry(airports, code);
	if (!found) return null;
	const [, municipality, country] = found;
	return [municipality, country ? isoAlpha2CountryName(country) : null].filter(Boolean).join(', ') || null;
}

/** The airline behind a designator, or null while the table loads or for a code it lacks. */
export function airlineName(airlines: AirlineTable | null, code: string | null): string | null {
	if (!code) return null;
	const key = code.toUpperCase();
	return AIRLINE_OVERRIDES[key]?.name ?? airlines?.[key] ?? null;
}

/** The airline where it is known, and the designator where it is not. */
export const airlineLabel = (airlines: AirlineTable | null, code: string): string =>
	airlineName(airlines, code) ?? code;
