// SPDX-FileCopyrightText: 2026 ave
// SPDX-License-Identifier: MIT OR EUPL-1.2

/**
 * Names for the codes a boarding pass is written in.
 *
 * BCBP names nothing. Its airports are three letter IATA codes and its
 * airlines two letter designators, so both tables exist only to turn a pass
 * back into somewhere and someone. They are generated by
 * scripts/build-airports.py and scripts/build-airlines.py and refreshed
 * monthly; the terms each one carries are in its `_note` and in
 * docs/credits.md, and the airline table's are the ones that bind.
 *
 * Both load on demand, so only flight tickets pay for them, and until they
 * arrive the codes show.
 *
 * Item 142, the three digit accounting code, is a different numbering from
 * the designator, and the airline table carries it beside each holder, so
 * `airlineByAccountingCode` resolves it. What is deliberately not resolved:
 * the metropolitan area codes such as LON and NYC, which stand for a city
 * rather than an airport and are in no airport catalogue.
 *
 * A designator outlives the airline that held it: IATA reassigns them, so AZ
 * is Alitalia on a pass from 2019 and ITA Airways on one from 2023. The
 * airline table therefore keeps every holder a code has had with the dates it
 * had it, and a lookup takes the flight date the pass already carries. Ask
 * without one and the answer is whoever holds the code now, which is right
 * for a pass being scanned at a gate and wrong for one out of a drawer.
 */
import { isoAlpha2CountryName } from '../countries.ts';
import { lazyTable } from '../lazy.ts';

/** Airport name, then the town it serves and its country where those are known. */
export type AirportEntry = [name: string, municipality?: string, country?: string];
export type AirportTable = Record<string, AirportEntry>;

/**
 * One airline's holding of one designator: its name, the dates it held the
 * code between, the three digit accounting code it bills under, and what it
 * carries. A blank date is an open end rather than an unknown one, and the
 * build script drops the fields that trail off blank.
 */
export type AirlineEntry = [
	name: string,
	from?: string,
	to?: string,
	accountingCode?: number,
	type?: string
];

/** Every holder each designator has had, oldest first. */
export type AirlineTable = Record<string, AirlineEntry[]>;

interface AirlineOverride {
	name: string;
	/** Where the identification comes from. */
	source: string;
}

/**
 * Anywhere this repo has a better answer than the table. Corrections go here
 * rather than into the JSON, so that regenerating stays a clean copy.
 *
 * Empty, and worth keeping empty. A designator that looks as if it needs an
 * entry here is usually one that changed hands, and the dated table answers
 * those itself: AZ from its validity dates, LH from the passenger type that
 * tells it apart from Lufthansa Cargo.
 *
 * An override answers for every date at once, so it belongs to a fact the
 * source has plainly wrong, never to a reassignment. Those are the table's
 * job, and putting one here would break the older passes that the previous
 * holder is the right answer for.
 */
const AIRLINE_OVERRIDES: Record<string, AirlineOverride> = {};

export const loadAirports = lazyTable(() =>
	import('../data/airports.json').then(
		// A JSON import widens every row to string[]. The build script writes
		// the name first and drops trailing blanks, which is what the tuple says.
		(m) => (m.default as unknown as { airports: AirportTable }).airports
	)
);

export const loadAirlines = lazyTable(() =>
	import('../data/airlines.json').then(
		// Widened the same way the airport rows are, and for the same reason:
		// the tuple is what the build script writes, not what JSON can say.
		(m) => (m.default as unknown as { airlines: AirlineTable }).airlines
	)
);

/**
 * The same for airports, which the table's `_note` points corrections at.
 * Empty. An entry replaces the whole row, so it carries the town and country
 * as well as the name, and a source like the airline ones.
 */
const AIRPORT_OVERRIDES: Record<string, { entry: AirportEntry; source: string }> = {};

const entry = (airports: AirportTable | null, code: string): AirportEntry | undefined => {
	if (!code) return undefined;
	const key = code.toUpperCase();
	return AIRPORT_OVERRIDES[key]?.entry ?? airports?.[key];
};

/**
 * What to put where the code went. The code itself until the table lands, and
 * for the codes it does not cover, since that is what the pass prints.
 */
export function airportName(airports: AirportTable | null, code: string): string {
	return entry(airports, code)?.[0] ?? code;
}

/**
 * The town and country behind the name, for the places a name alone does not
 * settle: Dulles is in Dulles, and the pass says Washington.
 */
export function airportPlace(airports: AirportTable | null, code: string): string | null {
	const found = entry(airports, code);
	if (!found) return null;
	const [, municipality, country] = found;
	return [municipality, country ? isoAlpha2CountryName(country) : null].filter(Boolean).join(', ') || null;
}

/**
 * Whether a holding covers a date. The source writes a handover as one
 * airline's `to` and the next one's `from` on the same day, so the day itself
 * belongs to the airline taking over: Alitalia stopped flying on 14 October
 * 2021 and ITA Airways started on the 15th, which is the date both records
 * carry.
 */
function holdsOn(entry: AirlineEntry, on: string | null): boolean {
	const [, from = '', to = ''] = entry;
	// Without a date the question is who holds the code now, so anything with
	// an end has already answered no.
	if (!on) return !to;
	return (!from || from <= on) && (!to || on < to);
}

/**
 * The holder to answer with. Where the dates leave more than one, a passenger
 * airline beats anything else: Lufthansa and Lufthansa Cargo both hold LH
 * today, and a boarding pass is a passenger document. Failing that the oldest
 * holding wins, which is arbitrary but at least the same answer every time;
 * the build script names the handful of codes this happens to.
 */
function holder(entries: AirlineEntry[], on: string | null): AirlineEntry | null {
	const valid = entries.filter((e) => holdsOn(e, on));
	return valid.find((e) => (e[4] ?? '').includes('P')) ?? valid[0] ?? null;
}

/**
 * The airline behind a designator on a given date, or null while the table
 * loads and for the codes it does not cover. `on` is an ISO date, normally
 * the leg's flight date; without one the answer is the current holder.
 */
export function airlineName(
	airlines: AirlineTable | null,
	code: string | null,
	on: string | null = null
): string | null {
	if (!code) return null;
	const key = code.toUpperCase();
	return AIRLINE_OVERRIDES[key]?.name ?? holder(airlines?.[key] ?? [], on)?.[0] ?? null;
}

/** The airline where it is known, and the designator where it is not. */
export const airlineLabel = (
	airlines: AirlineTable | null,
	code: string,
	on: string | null = null
): string => airlineName(airlines, code, on) ?? code;

/**
 * The airline behind item 142, the three digit accounting code, which is a
 * different numbering from the designator and the only other identification a
 * pass carries. Worth having because it answers where a designator does not.
 *
 * The code can pass from one airline to the next with the business, as 055
 * went from Alitalia to ITA Airways, so it is read against the flight date
 * like a designator. Where no holding covers that date, the answer stands
 * only if every holder of the code is the same airline; otherwise naming one
 * would be a guess about which.
 */
export function airlineByAccountingCode(
	airlines: AirlineTable | null,
	code: string | null,
	on: string | null = null
): string | null {
	if (!airlines || !code || !/^\d{1,3}$/.test(code.trim())) return null;
	const num = Number(code);
	if (!num) return null;
	const matches = Object.values(airlines)
		.flat()
		.filter((e) => e[3] === num);
	const dated = holder(matches, on);
	if (dated) return dated[0];
	const names = new Set(matches.map((e) => e[0]));
	return names.size === 1 ? [...names][0] : null;
}
