// SPDX-FileCopyrightText: 2026 ave
// SPDX-License-Identifier: MIT OR EUPL-1.2

/**
 * Names for the codes a boarding pass is written in.
 *
 * BCBP names nothing. Its airports are three letter IATA codes and its
 * airlines two letter designators, so both tables exist only to turn a pass
 * back into somewhere and someone. They are generated by
 * scripts/build-airports.py and scripts/build-airlines.py and refreshed
 * monthly; the terms each one carries are in its `_note` and in
 * docs/credits.md, and the airline table's are the ones that bind.
 *
 * Both load on demand, so only flight tickets pay for them, and until they
 * arrive the codes show, which is what happened before the tables existed.
 *
 * What is deliberately not resolved: item 142, the three digit accounting
 * code, which is a different numbering that neither source records; and the
 * metropolitan area codes such as LON and NYC, which stand for a city rather
 * than an airport and are in no airport catalogue.
 *
 * A designator outlives the airline that held it: IATA reassigns them, so AZ
 * is Alitalia on a pass from 2019 and ITA Airways on one from 2023. The
 * airline table therefore keeps every holder a code has had with the dates it
 * had it, and a lookup takes the flight date the pass already carries. Ask
 * without one and the answer is whoever holds the code now, which is right
 * for a pass being scanned at a gate and wrong for one out of a drawer.
 */
import { isoAlpha2CountryName } from '../countries.ts';

/** Airport name, then the town it serves and its country where those are known. */
export type AirportEntry = [name: string, municipality?: string, country?: string];
export type AirportTable = Record<string, AirportEntry>;

/**
 * One airline's holding of one designator: its name, the dates it held the
 * code between, the three digit accounting code it bills under, and what it
 * carries. A blank date is an open end rather than an unknown one, and the
 * build script drops the fields that trail off blank.
 */
export type AirlineEntry = [
	name: string,
	from?: string,
	to?: string,
	accountingCode?: number,
	type?: string
];

/** Every holder each designator has had, oldest first. */
export type AirlineTable = Record<string, AirlineEntry[]>;

interface AirlineOverride {
	name: string;
	/** Where the identification comes from. */
	source: string;
}

/**
 * Anywhere this repo has a better answer than the table. Corrections go here
 * rather than into the JSON, so that regenerating stays a clean copy.
 *
 * Empty, and worth keeping empty. The three entries this map used to hold
 * were all the source failing to say when a designator changed hands, and a
 * dated source answers them itself: AZ from its validity dates, LH from the
 * passenger type that tells it apart from Lufthansa Cargo, SQ because there
 * was never more than one holder to choose between.
 *
 * An override answers for every date at once, so it belongs to a fact the
 * source has plainly wrong, never to a reassignment. Those are the table's
 * job, and putting one here would break the older passes that the previous
 * holder is the right answer for.
 */
const AIRLINE_OVERRIDES: Record<string, AirlineOverride> = {};

let airportCache: AirportTable | null = null;
let airportPending: Promise<AirportTable> | null = null;

export async function loadAirports(): Promise<AirportTable> {
	if (airportCache) return airportCache;
	airportPending ??= import('../data/airports.json').then((m) => {
		// A JSON import widens every row to string[]. The build script writes
		// the name first and drops trailing blanks, which is what the tuple says.
		airportCache = (m.default as unknown as { airports: AirportTable }).airports;
		return airportCache;
	});
	return airportPending;
}

let airlineCache: AirlineTable | null = null;
let airlinePending: Promise<AirlineTable> | null = null;

export async function loadAirlines(): Promise<AirlineTable> {
	if (airlineCache) return airlineCache;
	airlinePending ??= import('../data/airlines.json').then((m) => {
		// Widened the same way the airport rows are, and for the same reason:
		// the tuple is what the build script writes, not what JSON can say.
		airlineCache = (m.default as unknown as { airlines: AirlineTable }).airlines;
		return airlineCache;
	});
	return airlinePending;
}

const entry = (airports: AirportTable | null, code: string): AirportEntry | undefined =>
	code ? airports?.[code.toUpperCase()] : undefined;

/**
 * What to put where the code went. The code itself until the table lands, and
 * for the codes it does not cover, since that is what the pass prints.
 */
export function airportName(airports: AirportTable | null, code: string): string {
	return entry(airports, code)?.[0] ?? code;
}

/**
 * The town and country behind the name, for the places a name alone does not
 * settle: Dulles is in Dulles, and the pass says Washington.
 */
export function airportPlace(airports: AirportTable | null, code: string): string | null {
	const found = entry(airports, code);
	if (!found) return null;
	const [, municipality, country] = found;
	return [municipality, country ? isoAlpha2CountryName(country) : null].filter(Boolean).join(', ') || null;
}

/**
 * Whether a holding covers a date. The source writes a handover as one
 * airline's `to` and the next one's `from` on the same day, so the day itself
 * belongs to the airline taking over: Alitalia stopped flying on 14 October
 * 2021 and ITA Airways started on the 15th, which is the date both records
 * carry.
 */
function holdsOn(entry: AirlineEntry, on: string | null): boolean {
	const [, from = '', to = ''] = entry;
	// Without a date the question is who holds the code now, so anything with
	// an end has already answered no.
	if (!on) return !to;
	return (!from || from <= on) && (!to || on < to);
}

/**
 * The holder to answer with. Where the dates leave more than one, a passenger
 * airline beats anything else: Lufthansa and Lufthansa Cargo both hold LH
 * today, and a boarding pass is a passenger document. Failing that the oldest
 * holding wins, which is arbitrary but at least the same answer every time;
 * the build script names the handful of codes this happens to.
 */
function holder(entries: AirlineEntry[], on: string | null): AirlineEntry | null {
	const valid = entries.filter((e) => holdsOn(e, on));
	return valid.find((e) => (e[4] ?? '').includes('P')) ?? valid[0] ?? null;
}

/**
 * The airline behind a designator on a given date, or null while the table
 * loads and for the codes it does not cover. `on` is an ISO date, normally
 * the leg's flight date; without one the answer is the current holder.
 */
export function airlineName(
	airlines: AirlineTable | null,
	code: string | null,
	on: string | null = null
): string | null {
	if (!code) return null;
	const key = code.toUpperCase();
	return AIRLINE_OVERRIDES[key]?.name ?? holder(airlines?.[key] ?? [], on)?.[0] ?? null;
}

/** The airline where it is known, and the designator where it is not. */
export const airlineLabel = (
	airlines: AirlineTable | null,
	code: string,
	on: string | null = null
): string => airlineName(airlines, code, on) ?? code;

/**
 * The airline behind item 142, the three digit accounting code, which is a
 * different numbering from the designator and the only other identification a
 * pass carries. Worth having because it answers where a designator does not:
 * the code the pass bills under does not change hands the way a two letter
 * one does.
 */
export function airlineByAccountingCode(
	airlines: AirlineTable | null,
	code: string | null,
	on: string | null = null
): string | null {
	if (!airlines || !code || !/^\d{1,3}$/.test(code.trim())) return null;
	const num = Number(code);
	if (!num) return null;
	const matches = Object.values(airlines)
		.flat()
		.filter((e) => e[3] === num);
	return holder(matches, on)?.[0] ?? matches[0]?.[0] ?? null;
}
